version: "3.8"
services:
  nginx:
    image: nginx:alpine
    container_name: gptmodel_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - techmodel-network
      - gateway_net
    restart: always
    depends_on:
      - techmodelapi
      - techmodelfrontend

  techmodelapi:
    image: viraj231/techmodelapi:latest
    container_name: techmodelapi
    restart: always
    networks:
      - techmodel-network

  techmodelfrontend:
    image: viraj231/techmodelfrontend:latest
    container_name: techmodelfrontend
    restart: always
    networks:
      - techmodel-network

networks:
  techmodel-network:
    driver: bridge
  gateway_net:
    external: true
